"""long

Revision ID: 081b85fd55e0
Revises: 4303c658629a
Create Date: 2019-10-14 14:21:56.676015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081b85fd55e0'
down_revision = '4303c658629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('airplane_id', sa.String(length=64), nullable=False))
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_id'], ['unique_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_column('flight', 'airplane_id')
    # ### end Alembic commands ###
