"""latest

Revision ID: 11fb26264a96
Revises: 156c327846ab
Create Date: 2019-11-15 15:18:52.686795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11fb26264a96'
down_revision = '156c327846ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flight_ibfk_3', 'flight', type_='foreignkey')
    op.create_foreign_key(None, 'flight', 'status', ['status'], ['status'])
    op.add_column('status', sa.Column('status', sa.String(length=64), nullable=False))
    op.drop_column('status', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('type', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('status', 'status')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.create_foreign_key('flight_ibfk_3', 'flight', 'status', ['status'], ['type'])
    # ### end Alembic commands ###
