"""long

Revision ID: 1438185b6c43
Revises: deabd69d22ea
Create Date: 2019-10-14 14:37:52.376438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1438185b6c43'
down_revision = 'deabd69d22ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airline_name'], ['airline_name'])
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_id'], ['unique_id'])
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_model'], ['model'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    # ### end Alembic commands ###
