"""latest

Revision ID: 156c327846ab
Revises: c91989ab46f0
Create Date: 2019-11-15 15:17:25.277119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156c327846ab'
down_revision = 'c91989ab46f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.add_column('flight', sa.Column('status', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'flight', 'status', ['status'], ['type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_column('flight', 'status')
    op.drop_table('status')
    # ### end Alembic commands ###
