"""latest

Revision ID: 1995dad3439f
Revises: f9e79d56fdb6
Create Date: 2019-11-15 14:07:01.361610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1995dad3439f'
down_revision = 'f9e79d56fdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flight', 'airport', ['departure'], ['name'])
    op.create_foreign_key('fk_flight_name_model_id', 'flight', 'airline_stock', ['airline_name', 'airplane_model', 'airplane_id'], ['airline_name', 'model', 'unique_id'])
    op.create_foreign_key(None, 'flight', 'airport', ['arrival'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint('fk_flight_name_model_id', 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    # ### end Alembic commands ###
