"""latest

Revision ID: 2de6ca6d238e
Revises: 11fb26264a96
Create Date: 2019-11-15 15:19:44.461499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de6ca6d238e'
down_revision = '11fb26264a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('status')
    )
    op.create_foreign_key(None, 'flight', 'status', ['status'], ['status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_table('status')
    # ### end Alembic commands ###
