"""long lat

Revision ID: 4303c658629a
Revises: bd5e728f257f
Create Date: 2019-10-14 13:58:16.318752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4303c658629a'
down_revision = 'bd5e728f257f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('airline_stock_ibfk_3', 'airline_stock', type_='foreignkey')
    op.drop_column('airline_stock', 'stationed')
    op.drop_constraint('flight_ibfk_2', 'flight', type_='foreignkey')
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_id'], ['unique_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.create_foreign_key('flight_ibfk_2', 'flight', 'airplane', ['airplane_id'], ['id_num'])
    op.add_column('airline_stock', sa.Column('stationed', mysql.VARCHAR(length=64), nullable=True))
    op.create_foreign_key('airline_stock_ibfk_3', 'airline_stock', 'airport', ['stationed'], ['name'])
    # ### end Alembic commands ###
