"""new update

Revision ID: 4a6957b75cff
Revises: 8cfe6d2f028f
Create Date: 2019-10-12 15:44:27.682373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6957b75cff'
down_revision = '8cfe6d2f028f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airport', sa.Column('country', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airport', 'country')
    # ### end Alembic commands ###
