"""drop password from booking_agent

Revision ID: 5196f3c3c455
Revises: a1cd1792974c
Create Date: 2019-11-19 12:13:36.820664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5196f3c3c455'
down_revision = 'a1cd1792974c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_agent', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_agent', sa.Column('password', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
