"""long

Revision ID: 88ceda5a0fe9
Revises: f23ffe964e0f
Create Date: 2019-10-14 14:47:29.222604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88ceda5a0fe9'
down_revision = 'f23ffe964e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight', 'airplane_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('flight', 'airplane_model',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_id'], ['unique_id'])
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_model'], ['model'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.alter_column('flight', 'airplane_model',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('flight', 'airplane_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
