"""latest update

Revision ID: 8cfe6d2f028f
Revises: 
Create Date: 2019-10-12 15:38:52.840540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cfe6d2f028f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airline_staff', 'password')
    op.add_column('airport', sa.Column('code', sa.String(length=3), nullable=True))
    op.create_unique_constraint(None, 'airport', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'airport', type_='unique')
    op.drop_column('airport', 'code')
    op.add_column('airline_staff', sa.Column('password', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
