"""latest

Revision ID: 9a32a8c66cbf
Revises: ceb5efa3a484
Create Date: 2019-11-15 14:02:07.679220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a32a8c66cbf'
down_revision = 'ceb5efa3a484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flight_ibfk_8', 'flight', type_='foreignkey')
    op.drop_constraint('flight_ibfk_6', 'flight', type_='foreignkey')
    op.drop_constraint('flight_ibfk_7', 'flight', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('flight_ibfk_7', 'flight', 'airline_stock', ['airplane_id'], ['unique_id'])
    op.create_foreign_key('flight_ibfk_6', 'flight', 'airline_stock', ['airline_name'], ['airline_name'])
    op.create_foreign_key('flight_ibfk_8', 'flight', 'airline_stock', ['airplane_model'], ['model'])
    # ### end Alembic commands ###
