"""long lat

Revision ID: bd5e728f257f
Revises: b72de3508458
Create Date: 2019-10-13 17:42:33.244617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd5e728f257f'
down_revision = 'b72de3508458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airline_stock', sa.Column('stationed', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'airline_stock', 'airport', ['stationed'], ['name'])
    op.add_column('flight', sa.Column('arrival_date', sa.DateTime(), nullable=False))
    op.add_column('flight', sa.Column('departure_date', sa.DateTime(), nullable=False))
    op.drop_column('flight', 'departure_time')
    op.drop_column('flight', 'arrival_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('arrival_time', mysql.DATETIME(), nullable=False))
    op.add_column('flight', sa.Column('departure_time', mysql.DATETIME(), nullable=False))
    op.drop_column('flight', 'departure_date')
    op.drop_column('flight', 'arrival_date')
    op.drop_constraint(None, 'airline_stock', type_='foreignkey')
    op.drop_column('airline_stock', 'stationed')
    # ### end Alembic commands ###
