"""latest

Revision ID: c91989ab46f0
Revises: 04b83b165860
Create Date: 2019-11-15 15:01:20.288720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91989ab46f0'
down_revision = '04b83b165860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('date_purchased', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'date_purchased')
    # ### end Alembic commands ###
