"""next

Revision ID: c9d86a774978
Revises: dc48f18359ae
Create Date: 2019-10-04 14:52:57.963115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9d86a774978'
down_revision = 'dc48f18359ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airplane', sa.Column('airline_name', sa.String(length=64), nullable=False))
    op.drop_constraint('airplane_ibfk_1', 'airplane', type_='foreignkey')
    op.create_foreign_key(None, 'airplane', 'airline', ['airline_name'], ['name'])
    op.drop_column('airplane', 'airline')
    op.add_column('customer', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('customer', 'password')
    op.add_column('flight', sa.Column('airline_name', sa.String(length=64), nullable=False))
    op.add_column('flight', sa.Column('airplane_id', sa.String(length=64), nullable=False))
    op.drop_constraint('flight_ibfk_1', 'flight', type_='foreignkey')
    op.drop_constraint('flight_ibfk_2', 'flight', type_='foreignkey')
    op.create_foreign_key(None, 'flight', 'airline', ['airline_name'], ['name'])
    op.create_foreign_key(None, 'flight', 'airplane', ['airplane_id'], ['id_num'])
    op.drop_column('flight', 'airplane')
    op.drop_column('flight', 'airline')
    op.add_column('ticket', sa.Column('airline_name', sa.String(length=64), nullable=False))
    op.add_column('ticket', sa.Column('flight_num', sa.String(length=64), nullable=False))
    op.drop_constraint('ticket_ibfk_1', 'ticket', type_='foreignkey')
    op.drop_constraint('ticket_ibfk_4', 'ticket', type_='foreignkey')
    op.create_foreign_key(None, 'ticket', 'flight', ['flight_num'], ['flight_num'])
    op.create_foreign_key(None, 'ticket', 'airline', ['airline_name'], ['name'])
    op.drop_column('ticket', 'flight')
    op.drop_column('ticket', 'airline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('airline', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('ticket', sa.Column('flight', mysql.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.create_foreign_key('ticket_ibfk_4', 'ticket', 'flight', ['flight'], ['flight_num'])
    op.create_foreign_key('ticket_ibfk_1', 'ticket', 'airline', ['airline'], ['name'])
    op.drop_column('ticket', 'flight_num')
    op.drop_column('ticket', 'airline_name')
    op.add_column('flight', sa.Column('airline', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('flight', sa.Column('airplane', mysql.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.create_foreign_key('flight_ibfk_2', 'flight', 'airplane', ['airplane'], ['id_num'])
    op.create_foreign_key('flight_ibfk_1', 'flight', 'airline', ['airline'], ['name'])
    op.drop_column('flight', 'airplane_id')
    op.drop_column('flight', 'airline_name')
    op.add_column('customer', sa.Column('password', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('customer', 'password_hash')
    op.add_column('airplane', sa.Column('airline', mysql.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'airplane', type_='foreignkey')
    op.create_foreign_key('airplane_ibfk_1', 'airplane', 'airline', ['airline'], ['name'])
    op.drop_column('airplane', 'airline_name')
    # ### end Alembic commands ###
