"""adding seats_left

Revision ID: ce076437448c
Revises: 3c1bad0d0fc7
Create Date: 2019-11-17 20:32:51.599379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce076437448c'
down_revision = '3c1bad0d0fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('seats_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'seats_left')
    # ### end Alembic commands ###
