"""latest

Revision ID: d2955400d2bb
Revises: 1995dad3439f
Create Date: 2019-11-15 14:15:19.229695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2955400d2bb'
down_revision = '1995dad3439f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_ticket_name_num', 'ticket', 'flight', ['airline_name', 'flight_num'], ['airline_name', 'flight_num'])
    op.create_foreign_key(None, 'ticket', 'customer', ['customer_email'], ['email'])
    op.create_foreign_key(None, 'ticket', 'booking_agent', ['booking_agent_ID'], ['booking_agent_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_constraint('fk_ticket_name_num', 'ticket', type_='foreignkey')
    # ### end Alembic commands ###
