"""empty message

Revision ID: dc48f18359ae
Revises: 
Create Date: 2019-10-03 21:16:51.579306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc48f18359ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('airport',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('booking_agent',
    sa.Column('booking_agent_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('booking_agent_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customer',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('passport_num', sa.String(length=64), nullable=False),
    sa.Column('passport_expir', sa.DateTime(), nullable=False),
    sa.Column('passport_country', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('address',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('building_num', sa.String(length=64), nullable=False),
    sa.Column('street', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['customer.email'], ),
    sa.PrimaryKeyConstraint('email', 'building_num', 'street', 'city', 'state', 'zip_code')
    )
    op.create_table('airline_staff',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('airline', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['airline'], ['airline.name'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('airplane',
    sa.Column('id_num', sa.String(length=64), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['airline'], ['airline.name'], ),
    sa.PrimaryKeyConstraint('id_num', 'airline')
    )
    op.create_table('phone_number',
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['customer.email'], ),
    sa.PrimaryKeyConstraint('email', 'number')
    )
    op.create_table('flight',
    sa.Column('flight_num', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('airline', sa.String(length=64), nullable=False),
    sa.Column('airplane', sa.String(length=64), nullable=False),
    sa.Column('arrival', sa.String(length=64), nullable=False),
    sa.Column('departure', sa.String(length=64), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airline'], ['airline.name'], ),
    sa.ForeignKeyConstraint(['airplane'], ['airplane.id_num'], ),
    sa.ForeignKeyConstraint(['arrival'], ['airport.name'], ),
    sa.ForeignKeyConstraint(['departure'], ['airport.name'], ),
    sa.PrimaryKeyConstraint('flight_num', 'airline')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=64), nullable=False),
    sa.Column('airline', sa.String(length=64), nullable=False),
    sa.Column('flight', sa.String(length=64), nullable=False),
    sa.Column('booking_agent_ID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['airline'], ['airline.name'], ),
    sa.ForeignKeyConstraint(['booking_agent_ID'], ['booking_agent.booking_agent_id'], ),
    sa.ForeignKeyConstraint(['customer_email'], ['customer.email'], ),
    sa.ForeignKeyConstraint(['flight'], ['flight.flight_num'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('flight')
    op.drop_table('phone_number')
    op.drop_table('airplane')
    op.drop_table('airline_staff')
    op.drop_table('address')
    op.drop_table('customer')
    op.drop_table('booking_agent')
    op.drop_table('airport')
    op.drop_table('airline')
    # ### end Alembic commands ###
