"""long

Revision ID: deabd69d22ea
Revises: 081b85fd55e0
Create Date: 2019-10-14 14:34:19.560968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deabd69d22ea'
down_revision = '081b85fd55e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('airplane_model', sa.String(length=64), nullable=True))
    op.drop_constraint('flight_ibfk_1', 'flight', type_='foreignkey')
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_id'], ['unique_id'])
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airplane_model'], ['model'])
    op.create_foreign_key(None, 'flight', 'airline_stock', ['airline_name'], ['airline_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.create_foreign_key('flight_ibfk_1', 'flight', 'airline', ['airline_name'], ['name'])
    op.drop_column('flight', 'airplane_model')
    # ### end Alembic commands ###
