"""updating user roles

Revision ID: eb06ce1bceeb
Revises: 2de6ca6d238e
Create Date: 2019-11-17 13:15:12.650005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb06ce1bceeb'
down_revision = '2de6ca6d238e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_role_default', table_name='role')
    op.drop_column('role', 'permissions')
    op.drop_column('role', 'default')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'role', ['role_id'], ['id'])
    op.add_column('role', sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_role_default', 'role', ['default'], unique=False)
    op.drop_table('user_roles')
    # ### end Alembic commands ###
