"""new airplane mech

Revision ID: f73992bf0ba6
Revises: 4a6957b75cff
Create Date: 2019-10-12 16:15:23.650538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f73992bf0ba6'
down_revision = '4a6957b75cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline_stock',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('unique_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['model'], ['airplane.id_num'], ),
    sa.ForeignKeyConstraint(['name'], ['airline.name'], ),
    sa.PrimaryKeyConstraint('name', 'model', 'unique_id')
    )
    op.add_column('airplane', sa.Column('aircraft_name', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'airplane', ['aircraft_name'])
    op.drop_constraint('airplane_ibfk_1', 'airplane', type_='foreignkey')
    op.drop_column('airplane', 'airline_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airplane', sa.Column('airline_name', mysql.VARCHAR(length=64), nullable=False))
    op.create_foreign_key('airplane_ibfk_1', 'airplane', 'airline', ['airline_name'], ['name'])
    op.drop_constraint(None, 'airplane', type_='unique')
    op.drop_column('airplane', 'aircraft_name')
    op.drop_table('airline_stock')
    # ### end Alembic commands ###
