"""latest

Revision ID: f9e79d56fdb6
Revises: 9a32a8c66cbf
Create Date: 2019-11-15 14:03:53.385328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e79d56fdb6'
down_revision = '9a32a8c66cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flight', 'airport', ['arrival'], ['name'])
    op.create_foreign_key(None, 'flight', 'airport', ['departure'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    # ### end Alembic commands ###
